name: pool_and_chill_app
description: "Pool & Chill Flutter App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  #API
  flutter_dotenv: ^5.1.0
  http: ^1.2.0
  flutter_secure_storage: ^9.0.0
  #formatting
  intl: ^0.19.0

  #icons
  cupertino_icons: ^1.0.8

  # UI / Design
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.7.0

  # state management
  url_launcher: ^6.3.0
  provider: ^6.1.5+1

  # Firebase
  firebase_core: ^2.24.0
  firebase_storage: ^11.6.0

  # Image picking & compression
  image_picker: ^1.0.7
  flutter_image_compress: ^2.1.0

  # Permissions
  permission_handler: ^11.2.0

  # Path provider (for temp files)
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env
